version: '3'
services:
  db:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_PASSWORD=ogochan'
      - 'POSTGRES_USER=ogochan'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ogochan -d ogochan"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: 'ghcr.io/waspcojp/hieronymus/hieronymus-web:latest'
    ports:
      - '3010:3010'
    working_dir: /app/hieronymus
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - HOME=/app/hieronymus
      - NODE_ENV=production
    init: true
volumes:
  postgres_data:   
