version: '3'
services:
  db:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_PASSWORD=hieronymus'
      - 'POSTGRES_USER=hieronymus'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: hieronymus-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hieronymus -d hieronymus"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: 'ghcr.io/beesnestinc/hieronymus/hieronymus-web:${DOCKER_IMAGE_VERSION:-v1}'
    ports:
      - '3010:3010'
    working_dir: /app/hieronymus
    depends_on:
      db:
        condition: service_healthy
    restart: always
    container_name: hieronymus-app
    environment:
      - HOME=/app/hieronymus
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=hieronymus
      - DB_PASSWORD=hieronymus
      - DB_NAME=hieronymus
      - BACKUP_DIR=/app/backups
    volumes:
      - backups_data:/app/backups
    init: true
volumes:
  postgres_data:   
  backups_data: